# Generated by Django 5.2.3 on 2025-07-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_statusclinete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr',
            field=models.ImageField(blank=True, help_text='QR gerado do usuário', null=True, upload_to='qr/'),
        ),
    ]
