# Generated by Django 5.2.3 on 2025-07-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave pix', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, help_text='Código para compartilhar', max_length=12),
        ),
    ]
