# Generated by Django 5.2.3 on 2025-07-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_chave_pix_alter_userprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave pix', max_length=80, null=True),
        ),
    ]
