# Generated by Django 5.2.3 on 2025-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco da chave Pix', max_length=80, null=True),
        ),
    ]
