# Generated by Django 5.2.3 on 2025-07-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, help_text='email', max_length=80, null=True),
        ),
    ]
