# Generated by Django 5.2.3 on 2025-07-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ano_carro',
            field=models.IntegerField(blank=True, default=0, help_text='Ano do carro do usuário', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo do carro do usario', max_length=60),
        ),
    ]
