# Generated by Django 5.2.3 on 2025-07-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_ano_carro_userprofile_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ano_carro',
            field=models.CharField(blank=True, help_text='Ano do carro do usuário', max_length=6, null=True),
        ),
    ]
