# Generated by Django 5.2.3 on 2025-07-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_ano_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='atendido_por',
            field=models.ManyToManyField(blank=True, help_text='Vendedoras responsáveis pelo atendimento', null=True, to='core.vendedora'),
        ),
    ]
