# Generated by Django 5.2.3 on 2025-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_atendido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='atendido_por',
            field=models.ManyToManyField(blank=True, help_text='Vendedoras responsáveis pelo atendimento', to='core.vendedora'),
        ),
    ]
